### ISSUE TITLE
ポップアップ通知が機能しない

### ISSUE THREAD

**Issue by Take1-Tata** [karno/StarryEyes#127]
当方、Surface Pro 3を使用しているのですが、
通知のポップアップが、スリム・ポップアップともに
機能しません。
通知がないと、ほかの作業中にわからないので
非常に不便です。
こちらの環境かもしれませんが、よろしくお願いします。

**Comment by mohemohe** [comment]
4K解像度でDPIスケーリングを200%に設定して使用していますが、同じように表示されません。
DPIスケーリングを100%に戻すと表示されるようになるのを確認しました。
物理ピクセルと論理ピクセルの変換がされていないような気がします。
