### ISSUE TITLE
ポップアップ通知がディスプレイの外に表示される

### ISSUE THREAD

**Issue by ueda-ay** [karno/StarryEyes#151]
通知に指定したディスプレイの表示領域よりも
右下にポップアップ表示される状況が発生しております。

[環境]
1. Accer AL2216W 1680ｘ1050
2. ノートPC（GALLERIA QF765HE）搭載ディスプレイ 1920 × 1080
※それぞれ単体で使用したときもデュアルディスプレイにしたときも
　発生します。

[症状]
・設定でディスプレイを指定したときの'notification are displayed into this screen'表記が
　右下にずれている。
・デュアルディスプレイ表示にし、通知させるディスプレイの右下にもう片方の
　ディスプレイを配置すると、もう片方のディスプレイの中途半端な位置に
　通知が確認できる。

上記の症状について、解決策等ありましたら
よろしくお願いします。

**Comment by karno** [comment]
タスクバーの位置は通常下端にあるかと思いますが、配置を変更していたりしますか？

**Comment by karno** [comment]
DPIをどこかで考慮し忘れている

**Comment by karno** [comment]
merged to #127 .
