### ISSUE TITLE
F-SecureにおいてKrile.exeがウイルス認定される

### ISSUE THREAD

**Issue by aoi-s** [karno/StarryEyes#156]
一時的なものかもしれませんが、一応レポートしておきます。

[概要]
F-SecureのリアルタイムスキャンでKrile.exeがTrojan.Generic.12776679( https://www.f-secure.com/v-descs/trojan_w32_generic.shtml )と判定され、隔離されてしまう。

[環境]
Windows 8.1
Krile STARRYEYES for Windows 2.9.47
F-Secure Client Security 10.00 build 415
F-Secure アンチウイルス 9.50 build 19031

[回避方法]
特になし。
隔離されたファイルは、復元してもすぐスキャンに引っかかります。
推奨できないですが、リアルタイムスキャンをオフにすれば取り敢えずしのげます。

**Comment by karno** [comment]
F-Secure の Sample Analysis System(https://analysis.f-secure.com/portal/login.html) に False Positive として登録しました。
処理されれば、回避されるものと思われます。今しばらくお待ちください。

**Comment by aoi-s** [comment]
対応有難うございました。
解消されましたらまた報告させていただきます。

**Comment by aoi-s** [comment]
遅くなってしましたが解消されました。対応していただきありがとうございました。

**Comment by karno** [comment]
解消されたとのこと
