### ISSUE TITLE
Krile上でのGoogle日本語入力のIME ON-OFF切り替えショートカットキーで落ちる (Win10)

### ISSUE THREAD

**Issue by erscl** [karno/StarryEyes#162]
Krile上でGoogle日本語入力のIME切り替えキーを押下するとKrileが動作を停止します。
（IME切替キーはデフォルトで英数、半角全角、かなキーなど）
また、言語バーから入力方式の切り替えが受け付けられません。（ひらがなを選んでも反映されないなど）
環境はWindows10、Krileのバージョンは2.9.47、GoogleIMEのバージョンは1.13.1641.0です。
同じバージョンの組み合わせでも発症しない例も確認できるため、Win10とGoogleIMEの相性問題な気もしたのですが一応報告させていただきます。

エラーの詳細な内容は以下のとおりです。

アプリケーション:Krile.exe
フレームワークのバージョン:v4.0.30319
説明: ハンドルされない例外のため、プロセスが中止されました。
例外情報:System.AccessViolationException
スタック:
   場所 MS.Win32.UnsafeNativeMethods+ITfKeystrokeMgr.TestKeyDown(Int32, Int32, Boolean ByRef)
   場所 MS.Win32.UnsafeNativeMethods+ITfKeystrokeMgr.TestKeyDown(Int32, Int32, Boolean ByRef)
   場所 System.Windows.Input.TextServicesContext.Keystroke(Int32, Int32, KeyOp)
   場所 System.Windows.Input.TextServicesManager.PreProcessInput(System.Object, System.Windows.Input.PreProcessInputEventArgs)
   場所 System.Windows.Input.InputManager.ProcessStagingArea()
   場所 System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   場所 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   場所 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(System.Windows.Interop.MSG ByRef, System.Windows.Input.ModifierKeys)
   場所 System.Windows.Interop.HwndSource.OnPreprocessMessage(System.Object)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   場所 System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority, System.Delegate, System.Object)
   場所 System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   場所 System.Windows.Interop.ThreadMessageEventHandler.Invoke(System.Windows.Interop.MSG ByRef, Boolean ByRef)
   場所 System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(System.Windows.Interop.MSG ByRef)
   場所 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   場所 System.Windows.Application.RunDispatcher(System.Object)
   場所 System.Windows.Application.RunInternal(System.Windows.Window)
   場所 StarryEyes.App.Main()

**Comment by karno** [comment]
IME周りで落ちることはままあるようで、WPFのバグ？

**Comment by erscl** [comment]
調べてみた感じおそらくWPFのバグのように思えます。
ちなみに追加情報となり申し訳ないのですが、Windows10をクリーンインストールした直後の同マシンでは不具合は発生せず、VisualStudioCommunity2015インストール後に発生するようになったため、.netあたりのバージョンも絡んだものではないかと推測しております。

**Comment by erscl** [comment]
追加情報です。Windows10の新ビルド、Build 10586を適用したところ問題が起こらなくなったのを確認しました。
サードパーティー製IMEとWPFのWindows10上で起こる相性問題だったのではないかと思います。
