### ISSUE TITLE
終了してもプロセスゾンビが残る

### ISSUE THREAD

**Issue by ssk-uo** [karno/StarryEyes#165]
残る。
こちらの環境ではv2.9.50のみで再現。

Win10 Pro 64bit

**Comment by karno** [comment]
リリースノートに記載済み。

App.Current.Exitで終了する目処は立っているが、そもそも何故終了しなくなったかがよくわからない。

**Comment by ssk-uo** [comment]
うわぁ恥ずかしい普通に書いてあった…
