### ISSUE TITLE
フォローしている鍵アカウントのツイートが取得できない時がある

### ISSUE THREAD

**Issue by tomo1560** [karno/StarryEyes#173]
フォローしている鍵アカウントが自動的に取得されず直接鍵アカウントのページを開き取得しないといけない時があります。
OS:Windows10Pro
Krile:3.0.0
また、取得しない鍵アカウントは最近作られたものだけのようです(5月以前に作られたアカウントは自動的に取得されてます)

**Comment by karno** [comment]
This issue may same reason for #174 and the scope of issue is smaller than #173. 
I want to keep tracking with moving this problem to #174.
